### ISSUE TITLE
Feature Request: BindAddress -Added sock param support

### ISSUE THREAD

**Issue by mzsombor** [ktbyers/nornir_netmiko#21]
Hi Kirk,

First of all thanks for the work you are doing for the community.

I recently started to use nornir but I could not find any option to specify the bind/source ip address for the netmiko connection plugin. After some digging I found out that this is done in netmiko via the sock parameter (which I guess is passed to paramiko):
https://github.com/ktbyers/netmiko/pull/1473

I could not figure out how to use this in nornir_netmiko so I made some adjustments to the code and added a new parameter in the `extras` field which can be used to create the socket:
https://github.com/ktbyers/nornir_netmiko/pull/20

It is working but I guess this is not the right way to do it. Could you please take a look and tell me if you can think of a tidier solution?

**Comment by mzsombor** [comment]
Thanks for the quick reply.

I'm quite new to nornir and I hope this is not a silly question but I could not find any reference in the nornir documentation.
Where should I create the socket in my code?

I currently have an inventory hosts.yaml:
```
cpe1.TEST:
    connection_options:
        netmiko:
            extras:
                ...
            timeout: 30
     hostname: 192.168.1.1
    password: test
    platform: terminal_server
    port: 22
    username: admin
```

and a nornir script

```

nr = InitNornir(
    runner={
        "plugin": "threaded",
        "options": {
            "num_workers": 50
        }
    },
    inventory={
        "plugin": "SimpleInventory",
        "options": {
            "host_file": "inventory/hosts.yaml",
            "group_file": "inventory/groups.yaml"
        }
    }
)
```

From the netmiko example I should use the following code to create a socket:
```
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.bind(('10.75.58.221', 0)) # The address to bind
sock.connect(('128.9.0.5', 22)) #The server address
```

The netmiko `extras` field is defined for every device in the hosts.yaml. Obviously the socket cannot be initialized in the yaml file. Does this mean that in my nornir script I should iterate over the inventory and append a socket to each device?
