### ISSUE TITLE
netmiko_send_command ,how can I use a key named "encoding"？

### ISSUE THREAD

**Issue by cqutopaz** [ktbyers/nornir_netmiko#37]
when I use InitNornir( ) and netmiko_send_command( ) ,
how can I give a keyword 'encoding'，and I can give my value to 'encoding' ?

**Comment by ktbyers** [comment]
All Netmiko arguments should be supported via `connection_options`

```yaml
group_name:
  platform: "ios"
  port: 22
  connection_options:
    netmiko:
      extras:
        encoding: "some_value"
```
